#!/usr/bin/env python3
import os
import rospy
from sensor_msgs.msg import Image
from vision_msgs.msg import Detection2D, Detection2DArray, ObjectHypothesisWithPose
from detector import Detector
import ros_numpy # pip3 install git+https://github.com/eric-wieser/ros_numpy
import rospkg


def rcv_image(msg):
    image = ros_numpy.numpify(msg)
    detections = mydetector(image)
    message = Detection2DArray()
    for clabel,score,box in zip(detections['detection_classes'], detections['detection_scores'], detections['detection_boxes']):
        d = Detection2D()
        d.bbox.size_x = box[3]-box[1]
        d.bbox.size_y = box[2]-box[0]
        d.bbox.center.x = box[1]+d.bbox.size_x/2
        d.bbox.center.y = box[0]+d.bbox.size_y/2
        o = ObjectHypothesisWithPose()
        o.score = score
        o.id = clabel
        d.results.append(o)
        message.detections.append(d)
    pub.publish(message)
    rospy.loginfo("published")


rospack = rospkg.RosPack()
DET_PATH=rospack.get_path('pepper_object_detection')+'efficientdet_d1_coco17_tpu-32'
mydetector = Detector(DET_PATH)

rospy.init_node('detector_node')

detection_topic = rospy.get_param('detection_topic')
input_image_topic = rospy.get_param('input_image_topic')
pub = rospy.Publisher(detection_topic, Detection2DArray, queue_size=2)
si = rospy.Subscriber(input_image_topic, Image, rcv_image)

rospy.loginfo('Detector initialized')

try:
    rospy.spin()
except KeyboardInterrupt:
    rospy.loginfo("Shutting down detector node")
    