pepper_cam_topic: /pepper_robot/camera/front/camera/image_raw
detector_path: <PATH>
dependencies_path: "" # Insert path to the folder wher you installed opencv-python, if you didn't install it system-wide